version: "3.9"

services:
  client:
    container_name: prakticum-client
    image: prakticum-client
    build:
      context: .
      dockerfile: Dockerfile.client
      args:
        CLIENT_PORT: ${CLIENT_PORT}
    restart: always
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      - CLIENT_PORT=${CLIENT_PORT}
      - SERVER_PORT=${SERVER_PORT}
    networks:
      - mynet

  server:
    container_name: prakticum-server
    env_file:
      - "./.env"
    build:
      context: .
      dockerfile: Dockerfile.server
      args:
        SERVER_PORT: ${SERVER_PORT}
    restart: always
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - mynet

  postgres:
    image: postgres:14
    env_file:
      - "./.env"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - ./tmp/pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    networks:
      - mynet

  nginx:
    image: nginx:latest
    ports:
      # Проброс порта 80 для HTTP
      - "80:80"
      # Проброс порта 443 для HTTPS
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/conf.d/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - certbot
      - client
      - server
    networks:
      - mynet

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt/:rw
      - ./certbot/www:/var/www/certbot/:rw
    # Команда для запуска в контейнере Certbot, которая обновляет сертификаты каждые 12 часов
    entrypoint: certbot certonly --webroot -w /var/www/certbot -d 51.250.29.150 --agree-tos --email juliusgerba@yandex.ru

    networks:
      - mynet

networks:
  mynet:
    driver: bridge
